image: ${REGISTRY:-}python:3.11-alpine

stages:
  - lint

pylint:
  tags:
    - python-datacenter
  stage: lint
  script:
    - apk add --no-cache git
    - python -m pip install --upgrade pip
    - pip install .[web]
    - pylint toolbox
